<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../plugin.props" />

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>Library</OutputType>
    <RootNamespace>HintServiceMeow</RootNamespace>
    <AssemblyName>HintServiceMeow</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;Exiled;Release</Configurations>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <Optimize>true</Optimize>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Exiled|AnyCPU'">
    <AssemblyName>HintServiceMeow-Exiled</AssemblyName>
    <Optimize>true</Optimize>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="$(LabAPIVersion)" IncludeAssets="compile" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="$(HarmonyVersion)" IncludeAssets="compile" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet" Version="$(YamlDotNetVersion)" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp-firstpass" HintPath="..\Dependencies\Assembly-CSharp-firstpass.dll" Private="False" />
    <Reference Include="Assembly-CSharp-publicized" HintPath="..\Dependencies\Assembly-CSharp-publicized.dll" Private="False" />
    <Reference Include="CommandSystem.Core" HintPath="..\Dependencies\CommandSystem.Core.dll" Private="False" />
    <Reference Include="Exiled.API" HintPath="..\Dependencies\Exiled.API.dll" Private="False" />
    <Reference Include="Exiled.Events" HintPath="..\Dependencies\Exiled.Events.dll" Private="False" />
    <Reference Include="Mirror" HintPath="..\Dependencies\Mirror.dll" Private="False" />
    <Reference Include="UnityEngine.CoreModule" HintPath="..\Dependencies\UnityEngine.CoreModule.dll" Private="False" />
    <Reference Include="System.IO.Compression" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="UpdateLog.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Update="UpdateLog.txt">
      <Pack>false</Pack>
    </None>
    <EmbeddedResource Include="TextWidth" />
  </ItemGroup>

</Project>